name: Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Run Linting checks, Unit Tests, record test and docstring coverage.
  Quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.11]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Configure Poetry
        run: python -m poetry config virtualenvs.in-project true
      - name: View poetry version
        run: poetry --version
      - name: Install Dependencies
        run: python -m poetry install -q
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python -m poetry run flake8 . --exclude .venv --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          python -m poetry run flake8 . --exclude .venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run black to check the code formattin
        run: |
          python -m pip install -q -U black
          python -m black --check .
      - name: Run pytest
        run: python -m poetry run pytest --cache-clear --cov-report term --cov-report xml:pytest-coverage.xml --cov=dataengineering tests/ > pytest-coverage.txt
      - name: Print Pytest Coverage Report
        uses: coroo/pytest-coverage-commentator@v1.0.2
        with:
          # This adds a comment with the pytest coverage report.
          pytest-coverage: pytest-coverage.txt
          token: ${{ github.token }}
      - name: Docstring Coverage
        run: |
          chmod +x ./scripts/docs-coverage.sh
          bash scripts/docs-coverage.sh
      - name: Comment with Docs Coverage on PR
        # only run if this is a PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: docs-coverage.txt
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
